### ISSUE TITLE
cert-manager-webhook-gandi cannot get resource secrets

### ISSUE THREAD

**Issue by vk496** [bwolf/cert-manager-webhook-gandi#12]
Hello,

I've tried to deploy the https://github.com/bwolf/cert-manager-webhook-gandi/pull/11 (which is already merged but missing the helm index.yaml) but I get the next error:

```
kubectl -n cert-manager describe Challenge
Name:         staging-wildcard-mydomain-com-nrqcw-313117991-3538039921
Namespace:    cert-manager
Labels:       <none>
Annotations:  <none>
API Version:  acme.cert-manager.io/v1
Kind:         Challenge
Metadata:
  Creation Timestamp:  2021-10-22T07:42:34Z
  Finalizers:
    finalizer.acme.cert-manager.io
  Generation:  1
  Managed Fields:
    API Version:  acme.cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizer.acme.cert-manager.io":
        f:ownerReferences:
          .:
          k:{"uid":"f5232e50-fe3b-4cce-88db-2bd4a8e40efa"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:authorizationURL:
        f:dnsName:
        f:issuerRef:
          .:
          f:kind:
          f:name:
        f:key:
        f:solver:
          .:
          f:dns01:
            .:
            f:webhook:
              .:
              f:config:
              f:groupName:
              f:solverName:
        f:token:
        f:type:
        f:url:
        f:wildcard:
      f:status:
        .:
        f:presented:
        f:processing:
        f:reason:
        f:state:
    Manager:    controller
    Operation:  Update
    Time:       2021-10-22T07:43:19Z
  Owner References:
    API Version:           acme.cert-manager.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Order
    Name:                  staging-wildcard-mydomain-com-nrqcw-313117991
    UID:                   f5232e50-fe3b-4cce-88db-2bd4a8e40efa
  Resource Version:        2161769
  Self Link:               /apis/acme.cert-manager.io/v1/namespaces/cert-manager/challenges/staging-wildcard-mydomain-com-nrqcw-313117991-3538039921
  UID:                     c3b73544-5fdb-4c23-9f5e-adb5bbbf381b
Spec:
  Authorization URL:  https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/755711798
  Dns Name:           mydomain.com
  Issuer Ref:
    Kind:  ClusterIssuer
    Name:  letsencrypt-staging
  Key:     mA2hM92XoAA0nxzdqmuEpwu3CyqLaq-Lu3t4r3KtSP4
  Solver:
    dns01:
      Webhook:
        Config:
          API Key Secret Ref:
            Key:      api-token
            Name:     dns-credentials-gandi
        Group Name:   acme.h6s.io
        Solver Name:  gandi
  Token:              OcooaAx3gD-aPTJCAFRke6m_fPBlTY8NGPm4YSTjxWA
  Type:               DNS-01
  URL:                https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/755711798/EuOuuw
  Wildcard:           true
Status:
  Presented:   false
  Processing:  true
  Reason:      unable to get API key: unable to get secret `dns-credentials-gandi`; secrets "dns-credentials-gandi" is forbidden: User "system:serviceaccount:cert-manager:cert-manager-webhook-gandi" cannot get resource "secrets" in API group "" in the namespace "cert-manager"
  State:       pending
Events:
  Type     Reason        Age                  From          Message
  ----     ------        ----                 ----          -------
  Normal   Started       3m46s                cert-manager  Challenge scheduled for processing
  Warning  PresentError  81s (x6 over 3m46s)  cert-manager  Error presenting challenge: unable to get API key: unable to get secret `dns-credentials-gandi`; secrets "dns-credentials-gandi" is forbidden: User "system:serviceaccount:cert-manager:cert-manager-webhook-gandi" cannot get resource "secrets" in API group "" in the namespace "cert-manager"
```

To reproduce the problem:

```bash
# cert-manager
helm upgrade cert-manager jetstack/cert-manager \
	-n cert-manager \
	--namespace cert-manager \
	--install \
	--wait \
	--create-namespace \
	--set installCRDs=true \
	--version v1.5.4

# webhook-gandi
# TODO: Use @bwolf repo when PR merged. Meanwhile, the groupName must rest as acme.h6s.io
helm upgrade cert-manager-webhook-gandi cert-manager-webhook-gandi \
	--namespace cert-manager \
	--install \
	--wait \
	--repo https://hexa-solutions.github.io/cert-manager-webhook-gandi \
	--version v0.2.0 \
	--set logLevel=2
```

Created the secret with:

`kubectl -n cert-manager create secret generic dns-credentials-gandi --from-literal=api-token='HEHEHE'`

(Verified that token is working)

and the resources

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  labels:
    group: mydom-certs # IMPORTANT!
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: secret@secret.secret
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: acme.h6s.io
            solverName: gandi
            config:
              apiKeySecretRef:
                key: api-token
                name: dns-credentials-gandi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-wildcard-mydomain-com
  namespace: cert-manager
  labels:
    group: mydom-certs # IMPORTANT!
spec:
  secretName: staging-wildcard-mydomain-com
  dnsNames:
    - "*.mydomain.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
```
