### ISSUE TITLE
Challenge Header error

### ISSUE THREAD

**Issue by seuf** [bwolf/cert-manager-webhook-gandi#23]
Hi,

I'm trying to set up acme certificates with the gandi webhook, but I have an error during the Challenge : 

```
Error presenting challenge: unable to check TXT record: Get "https://api.gandi.net/v5/livedns/domains/mydomain.comrecords/_acme-challenge.staging/TXT": net/http: invalid header field value "Apikey my_api_key\n" for key Authorization
```

Is the `\n` character normal ?

I've checked my secret and the apikey does not contain "\n"..

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/instance: certificates
  name: lets-encrypt-issuer
  namespace: cert-manager
spec:
  acme:
    email:myemail@example.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            apiKeySecretRef:
              key: api-token
              name: gandi-credentials
          groupName: acme.bwolf.me
          solverName: gandi
```

And my certificate : 

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: certificates
  name: traefik-certificate
  namespace: traefik
spec:
  dnsNames:
  - '*.mydomain.com'
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-issuer
  secretName: traefik-public-cert
```
and my secret 

```
apiVersion: v1
kind: Secret
metadata:
  name: gandi-credentials
  namespace: cert-manager
type: Opaque
data:
  api-token:  <base64 encoded apikey>
```
